# Generated by Django 3.1 on 2020-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie')),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('A', 'Action'), ('C', 'Comedy'), ('D', 'Drama'), ('R', 'Romance')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'English'), ('DR', 'Dari')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'Recently added'), ('MW', 'Most watched'), ('TR', 'Top rated')], max_length=2)),
                ('year_of_production', models.DateField()),
            ],
        ),
    ]
